export const BD_LOCATIONS = [
  {
    name: 'Dhaka',
    nameBn: 'ঢাকা',
    districts: [
      { name: 'Dhaka', nameBn: 'ঢাকা' },
      { name: 'Gazipur', nameBn: 'গাজীপুর' },
      { name: 'Narayanganj', nameBn: 'নারায়ণগঞ্জ' },
      { name: 'Narsingdi', nameBn: 'নরসিংদী' },
      { name: 'Manikganj', nameBn: 'মানিকগঞ্জ' },
      { name: 'Munshiganj', nameBn: 'মুন্সীগঞ্জ' },
      { name: 'Rajbari', nameBn: 'রাজবাড়ী' },
      { name: 'Madaripur', nameBn: 'মাদারীপুর' },
      { name: 'Shariatpur', nameBn: 'শরীয়তপুর' },
      { name: 'Faridpur', nameBn: 'ফরিদপুর' },
      { name: 'Gopalganj', nameBn: 'গোপালগঞ্জ' },
      { name: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ' },
      { name: 'Tangail', nameBn: 'টাঙ্গাইল' },
    ],
  },
  {
    name: 'Chittagong',
    nameBn: 'চট্টগ্রাম',
    districts: [
      { name: 'Chittagong', nameBn: 'চট্টগ্রাম' },
      { name: "Cox's Bazar", nameBn: "কক্সবাজার" },
      { name: 'Rangamati', nameBn: 'রাঙামাটি' },
      { name: 'Bandarban', nameBn: 'বান্দরবান' },
      { name: 'Khagrachhari', nameBn: 'খাগড়াছড়ি' },
      { name: 'Feni', nameBn: 'ফেনী' },
      { name: 'Lakshmipur', nameBn: 'লক্ষ্মীপুর' },
      { name: 'Chandpur', nameBn: 'চাঁদপুর' },
      { name: 'Comilla', nameBn: 'কুমিল্লা' },
      { name: 'Brahmanbaria', nameBn: 'ব্রাহ্মণবাড়িয়া' },
      { name: 'Noakhali', nameBn: 'নোয়াখালী' },
    ],
  },
  {
    name: 'Rajshahi',
    nameBn: 'রাজশাহী',
    districts: [
      { name: 'Rajshahi', nameBn: 'রাজশাহী' },
      { name: 'Chapainawabganj', nameBn: 'চাঁপাইনবাবগঞ্জ' },
      { name: 'Natore', nameBn: 'নাটোর' },
      { name: 'Naogaon', nameBn: 'নওগাঁ' },
      { name: 'Pabna', nameBn: 'পাবনা' },
      { name: 'Sirajganj', nameBn: 'সিরাজগঞ্জ' },
      { name: 'Bogura', nameBn: 'বগুড়া' },
      { name: 'Joypurhat', nameBn: 'জয়পুরহাট' },
    ],
  },
  {
    name: 'Khulna',
    nameBn: 'খুলনা',
    districts: [
      { name: 'Khulna', nameBn: 'খুলনা' },
      { name: 'Bagerhat', nameBn: 'বাগেরহাট' },
      { name: 'Satkhira', nameBn: 'সাতক্ষীরা' },
      { name: 'Jessore', nameBn: 'যশোর' },
      { name: 'Magura', nameBn: 'মাগুরা' },
      { name: 'Narail', nameBn: 'নড়াইল' },
      { name: 'Chuadanga', nameBn: 'চুয়াডাঙ্গা' },
      { name: 'Meherpur', nameBn: 'মেহেরপুর' },
      { name: 'Kushtia', nameBn: 'কুষ্টিয়া' },
      { name: 'Jhenaidah', nameBn: 'ঝিনাইদহ' },
    ],
  },
  {
    name: 'Sylhet',
    nameBn: 'সিলেট',
    districts: [
      { name: 'Sylhet', nameBn: 'সিলেট' },
      { name: 'Moulvibazar', nameBn: 'মৌলভীবাজার' },
      { name: 'Habiganj', nameBn: 'হবিগঞ্জ' },
      { name: 'Sunamganj', nameBn: 'সুনামগঞ্জ' },
    ],
  },
  {
    name: 'Barisal',
    nameBn: 'বরিশাল',
    districts: [
      { name: 'Barisal', nameBn: 'বরিশাল' },
      { name: 'Bhola', nameBn: 'ভোলা' },
      { name: 'Patuakhali', nameBn: 'পটুয়াখালী' },
      { name: 'Pirojpur', nameBn: 'পিরোজপুর' },
      { name: 'Jhalokati', nameBn: 'ঝালকাঠি' },
      { name: 'Barguna', nameBn: 'বরগুনা' },
    ],
  },
  {
    name: 'Rangpur',
    nameBn: 'রংপুর',
    districts: [
      { name: 'Rangpur', nameBn: 'রংপুর' },
      { name: 'Dinajpur', nameBn: 'দিনাজপুর' },
      { name: 'Thakurgaon', nameBn: 'ঠাকুরগাঁও' },
      { name: 'Panchagarh', nameBn: 'পঞ্চগড়' },
      { name: 'Nilphamari', nameBn: 'নীলফামারী' },
      { name: 'Lalmonirhat', nameBn: 'লালমনিরহাট' },
      { name: 'Kurigram', nameBn: 'কুড়িগ্রাম' },
      { name: 'Gaibandha', nameBn: 'গাইবান্ধা' },
    ],
  },
  {
    name: 'Mymensingh',
    nameBn: 'ময়মনসিংহ',
    districts: [
      { name: 'Mymensingh', nameBn: 'ময়মনসিংহ' },
      { name: 'Jamalpur', nameBn: 'জামালপুর' },
      { name: 'Sherpur', nameBn: 'শেরপুর' },
      { name: 'Netrokona', nameBn: 'নেত্রকোণা' },
    ],
  },
]
