export const SUBSCRIPTION_PLANS = {
  BASIC: {
    id: 'BASIC',
    name: 'বেসিক',
    price: 1500,
    duration: 30,
    maxListings: 20,
    featuredSlots: 0,
    badge: true,
    prioritySupport: false,
    dedicatedPage: false,
    analytics: false,
    color: '#166A47',
    bg: '#E8F5EE',
    popular: false,
    features: ['২০টা পর্যন্ত listing', 'Verified broker badge', 'সব district-এ listing', 'Email support'],
    notIncluded: ['Featured slots', 'Analytics dashboard', 'Dedicated broker page'],
  },
  PRO: {
    id: 'PRO',
    name: 'প্রো',
    price: 3000,
    duration: 30,
    maxListings: 50,
    featuredSlots: 5,
    badge: true,
    prioritySupport: true,
    dedicatedPage: false,
    analytics: true,
    color: '#1D4ED8',
    bg: '#DBEAFE',
    popular: true,
    features: ['৫০টা পর্যন্ত listing', 'Verified broker badge', '৫টা featured listing/মাস', 'Analytics dashboard', 'Priority support'],
    notIncluded: ['Dedicated broker page'],
  },
  ENTERPRISE: {
    id: 'ENTERPRISE',
    name: 'এন্টারপ্রাইজ',
    price: 5000,
    duration: 30,
    maxListings: 999,
    featuredSlots: 20,
    badge: true,
    prioritySupport: true,
    dedicatedPage: true,
    analytics: true,
    color: '#7C3AED',
    bg: '#EDE9FE',
    popular: false,
    features: ['Unlimited listing', 'Verified broker badge', '২০টা featured listing/মাস', 'Analytics dashboard', 'Dedicated broker page', 'Phone support', 'Custom profile banner'],
    notIncluded: [],
  },
} as const

export type PlanId = keyof typeof SUBSCRIPTION_PLANS
